# Generated by Django 5.2.11 on 2026-03-25 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200)),
                ('matn', models.TextField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='postlar/')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_sana', models.DateTimeField(auto_now=True)),
                ('nashr_etilgan', models.BooleanField(default=True)),
                ('korildi', models.IntegerField(default=0)),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostRasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='post_rasmlari/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(default='profillar/default.jpg', upload_to='profillar/')),
                ('cover_rasm', models.ImageField(blank=True, null=True, upload_to='cover/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('tugilgan_sana', models.DateField(blank=True, null=True)),
                ('manzil', models.CharField(blank=True, max_length=200)),
                ('foydalanuvchi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
