name: Deploy to AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy qilish
    runs-on: ubuntu-latest
    needs: test  # Test job o'tgandan keyin

    steps:
    - name: Kodni Yuklab Olish
      uses: actions/checkout@v3

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to EC2
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} '
          cd /var/www/blog &&
          git pull origin main &&
          source venv/bin/activate &&
          pip install -r requirements.txt &&
          python manage.py migrate &&
          python manage.py collectstatic --noinput &&
          sudo systemctl restart gunicorn &&
          sudo systemctl restart nginx
        '